/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ClassesRouteImport } from './routes/classes'
import { Route as AssignmentsRouteImport } from './routes/assignments'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as OrgIndexRouteImport } from './routes/$org/index'
import { Route as OrgClassesIndexRouteImport } from './routes/$org/classes/index'
import { Route as OrgClassroomIndexRouteImport } from './routes/$org/$classroom/index'
import { Route as OrgClassesNewIndexRouteImport } from './routes/$org/classes/new/index'
import { Route as OrgClassroomStudentsIndexRouteImport } from './routes/$org/$classroom/students/index'
import { Route as OrgClassroomAssignmentsIndexRouteImport } from './routes/$org/$classroom/assignments/index'
import { Route as OrgClassroomAssignmentsNewIndexRouteImport } from './routes/$org/$classroom/assignments/new/index'
import { Route as OrgClassroomAssignmentsAssignmentIndexRouteImport } from './routes/$org/$classroom/assignments/$assignment/index'
import { Route as OrgClassroomAssignmentsAssignmentSubmissionsIndexRouteImport } from './routes/$org/$classroom/assignments/$assignment/submissions/index'
import { Route as OrgClassroomAssignmentsAssignmentAcceptIndexRouteImport } from './routes/$org/$classroom/assignments/$assignment/accept/index'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassesRoute = ClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => rootRouteImport,
} as any)
const AssignmentsRoute = AssignmentsRouteImport.update({
  id: '/assignments',
  path: '/assignments',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgIndexRoute = OrgIndexRouteImport.update({
  id: '/$org/',
  path: '/$org/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgClassesIndexRoute = OrgClassesIndexRouteImport.update({
  id: '/$org/classes/',
  path: '/$org/classes/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgClassroomIndexRoute = OrgClassroomIndexRouteImport.update({
  id: '/$org/$classroom/',
  path: '/$org/$classroom/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgClassesNewIndexRoute = OrgClassesNewIndexRouteImport.update({
  id: '/$org/classes/new/',
  path: '/$org/classes/new/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgClassroomStudentsIndexRoute =
  OrgClassroomStudentsIndexRouteImport.update({
    id: '/$org/$classroom/students/',
    path: '/$org/$classroom/students/',
    getParentRoute: () => rootRouteImport,
  } as any)
const OrgClassroomAssignmentsIndexRoute =
  OrgClassroomAssignmentsIndexRouteImport.update({
    id: '/$org/$classroom/assignments/',
    path: '/$org/$classroom/assignments/',
    getParentRoute: () => rootRouteImport,
  } as any)
const OrgClassroomAssignmentsNewIndexRoute =
  OrgClassroomAssignmentsNewIndexRouteImport.update({
    id: '/$org/$classroom/assignments/new/',
    path: '/$org/$classroom/assignments/new/',
    getParentRoute: () => rootRouteImport,
  } as any)
const OrgClassroomAssignmentsAssignmentIndexRoute =
  OrgClassroomAssignmentsAssignmentIndexRouteImport.update({
    id: '/$org/$classroom/assignments/$assignment/',
    path: '/$org/$classroom/assignments/$assignment/',
    getParentRoute: () => rootRouteImport,
  } as any)
const OrgClassroomAssignmentsAssignmentSubmissionsIndexRoute =
  OrgClassroomAssignmentsAssignmentSubmissionsIndexRouteImport.update({
    id: '/$org/$classroom/assignments/$assignment/submissions/',
    path: '/$org/$classroom/assignments/$assignment/submissions/',
    getParentRoute: () => rootRouteImport,
  } as any)
const OrgClassroomAssignmentsAssignmentAcceptIndexRoute =
  OrgClassroomAssignmentsAssignmentAcceptIndexRouteImport.update({
    id: '/$org/$classroom/assignments/$assignment/accept/',
    path: '/$org/$classroom/assignments/$assignment/accept/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assignments': typeof AssignmentsRoute
  '/classes': typeof ClassesRoute
  '/login': typeof LoginRoute
  '/$org/': typeof OrgIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/$org/$classroom/': typeof OrgClassroomIndexRoute
  '/$org/classes/': typeof OrgClassesIndexRoute
  '/$org/$classroom/assignments/': typeof OrgClassroomAssignmentsIndexRoute
  '/$org/$classroom/students/': typeof OrgClassroomStudentsIndexRoute
  '/$org/classes/new/': typeof OrgClassesNewIndexRoute
  '/$org/$classroom/assignments/$assignment/': typeof OrgClassroomAssignmentsAssignmentIndexRoute
  '/$org/$classroom/assignments/new/': typeof OrgClassroomAssignmentsNewIndexRoute
  '/$org/$classroom/assignments/$assignment/accept/': typeof OrgClassroomAssignmentsAssignmentAcceptIndexRoute
  '/$org/$classroom/assignments/$assignment/submissions/': typeof OrgClassroomAssignmentsAssignmentSubmissionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assignments': typeof AssignmentsRoute
  '/classes': typeof ClassesRoute
  '/login': typeof LoginRoute
  '/$org': typeof OrgIndexRoute
  '/auth': typeof AuthIndexRoute
  '/$org/$classroom': typeof OrgClassroomIndexRoute
  '/$org/classes': typeof OrgClassesIndexRoute
  '/$org/$classroom/assignments': typeof OrgClassroomAssignmentsIndexRoute
  '/$org/$classroom/students': typeof OrgClassroomStudentsIndexRoute
  '/$org/classes/new': typeof OrgClassesNewIndexRoute
  '/$org/$classroom/assignments/$assignment': typeof OrgClassroomAssignmentsAssignmentIndexRoute
  '/$org/$classroom/assignments/new': typeof OrgClassroomAssignmentsNewIndexRoute
  '/$org/$classroom/assignments/$assignment/accept': typeof OrgClassroomAssignmentsAssignmentAcceptIndexRoute
  '/$org/$classroom/assignments/$assignment/submissions': typeof OrgClassroomAssignmentsAssignmentSubmissionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assignments': typeof AssignmentsRoute
  '/classes': typeof ClassesRoute
  '/login': typeof LoginRoute
  '/$org/': typeof OrgIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/$org/$classroom/': typeof OrgClassroomIndexRoute
  '/$org/classes/': typeof OrgClassesIndexRoute
  '/$org/$classroom/assignments/': typeof OrgClassroomAssignmentsIndexRoute
  '/$org/$classroom/students/': typeof OrgClassroomStudentsIndexRoute
  '/$org/classes/new/': typeof OrgClassesNewIndexRoute
  '/$org/$classroom/assignments/$assignment/': typeof OrgClassroomAssignmentsAssignmentIndexRoute
  '/$org/$classroom/assignments/new/': typeof OrgClassroomAssignmentsNewIndexRoute
  '/$org/$classroom/assignments/$assignment/accept/': typeof OrgClassroomAssignmentsAssignmentAcceptIndexRoute
  '/$org/$classroom/assignments/$assignment/submissions/': typeof OrgClassroomAssignmentsAssignmentSubmissionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assignments'
    | '/classes'
    | '/login'
    | '/$org/'
    | '/auth/'
    | '/$org/$classroom/'
    | '/$org/classes/'
    | '/$org/$classroom/assignments/'
    | '/$org/$classroom/students/'
    | '/$org/classes/new/'
    | '/$org/$classroom/assignments/$assignment/'
    | '/$org/$classroom/assignments/new/'
    | '/$org/$classroom/assignments/$assignment/accept/'
    | '/$org/$classroom/assignments/$assignment/submissions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assignments'
    | '/classes'
    | '/login'
    | '/$org'
    | '/auth'
    | '/$org/$classroom'
    | '/$org/classes'
    | '/$org/$classroom/assignments'
    | '/$org/$classroom/students'
    | '/$org/classes/new'
    | '/$org/$classroom/assignments/$assignment'
    | '/$org/$classroom/assignments/new'
    | '/$org/$classroom/assignments/$assignment/accept'
    | '/$org/$classroom/assignments/$assignment/submissions'
  id:
    | '__root__'
    | '/'
    | '/assignments'
    | '/classes'
    | '/login'
    | '/$org/'
    | '/auth/'
    | '/$org/$classroom/'
    | '/$org/classes/'
    | '/$org/$classroom/assignments/'
    | '/$org/$classroom/students/'
    | '/$org/classes/new/'
    | '/$org/$classroom/assignments/$assignment/'
    | '/$org/$classroom/assignments/new/'
    | '/$org/$classroom/assignments/$assignment/accept/'
    | '/$org/$classroom/assignments/$assignment/submissions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssignmentsRoute: typeof AssignmentsRoute
  ClassesRoute: typeof ClassesRoute
  LoginRoute: typeof LoginRoute
  OrgIndexRoute: typeof OrgIndexRoute
  AuthIndexRoute: typeof AuthIndexRoute
  OrgClassroomIndexRoute: typeof OrgClassroomIndexRoute
  OrgClassesIndexRoute: typeof OrgClassesIndexRoute
  OrgClassroomAssignmentsIndexRoute: typeof OrgClassroomAssignmentsIndexRoute
  OrgClassroomStudentsIndexRoute: typeof OrgClassroomStudentsIndexRoute
  OrgClassesNewIndexRoute: typeof OrgClassesNewIndexRoute
  OrgClassroomAssignmentsAssignmentIndexRoute: typeof OrgClassroomAssignmentsAssignmentIndexRoute
  OrgClassroomAssignmentsNewIndexRoute: typeof OrgClassroomAssignmentsNewIndexRoute
  OrgClassroomAssignmentsAssignmentAcceptIndexRoute: typeof OrgClassroomAssignmentsAssignmentAcceptIndexRoute
  OrgClassroomAssignmentsAssignmentSubmissionsIndexRoute: typeof OrgClassroomAssignmentsAssignmentSubmissionsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classes': {
      id: '/classes'
      path: '/classes'
      fullPath: '/classes'
      preLoaderRoute: typeof ClassesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assignments': {
      id: '/assignments'
      path: '/assignments'
      fullPath: '/assignments'
      preLoaderRoute: typeof AssignmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/auth'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$org/': {
      id: '/$org/'
      path: '/$org'
      fullPath: '/$org/'
      preLoaderRoute: typeof OrgIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$org/classes/': {
      id: '/$org/classes/'
      path: '/$org/classes'
      fullPath: '/$org/classes/'
      preLoaderRoute: typeof OrgClassesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$org/$classroom/': {
      id: '/$org/$classroom/'
      path: '/$org/$classroom'
      fullPath: '/$org/$classroom/'
      preLoaderRoute: typeof OrgClassroomIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$org/classes/new/': {
      id: '/$org/classes/new/'
      path: '/$org/classes/new'
      fullPath: '/$org/classes/new/'
      preLoaderRoute: typeof OrgClassesNewIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$org/$classroom/students/': {
      id: '/$org/$classroom/students/'
      path: '/$org/$classroom/students'
      fullPath: '/$org/$classroom/students/'
      preLoaderRoute: typeof OrgClassroomStudentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$org/$classroom/assignments/': {
      id: '/$org/$classroom/assignments/'
      path: '/$org/$classroom/assignments'
      fullPath: '/$org/$classroom/assignments/'
      preLoaderRoute: typeof OrgClassroomAssignmentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$org/$classroom/assignments/new/': {
      id: '/$org/$classroom/assignments/new/'
      path: '/$org/$classroom/assignments/new'
      fullPath: '/$org/$classroom/assignments/new/'
      preLoaderRoute: typeof OrgClassroomAssignmentsNewIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$org/$classroom/assignments/$assignment/': {
      id: '/$org/$classroom/assignments/$assignment/'
      path: '/$org/$classroom/assignments/$assignment'
      fullPath: '/$org/$classroom/assignments/$assignment/'
      preLoaderRoute: typeof OrgClassroomAssignmentsAssignmentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$org/$classroom/assignments/$assignment/submissions/': {
      id: '/$org/$classroom/assignments/$assignment/submissions/'
      path: '/$org/$classroom/assignments/$assignment/submissions'
      fullPath: '/$org/$classroom/assignments/$assignment/submissions/'
      preLoaderRoute: typeof OrgClassroomAssignmentsAssignmentSubmissionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$org/$classroom/assignments/$assignment/accept/': {
      id: '/$org/$classroom/assignments/$assignment/accept/'
      path: '/$org/$classroom/assignments/$assignment/accept'
      fullPath: '/$org/$classroom/assignments/$assignment/accept/'
      preLoaderRoute: typeof OrgClassroomAssignmentsAssignmentAcceptIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssignmentsRoute: AssignmentsRoute,
  ClassesRoute: ClassesRoute,
  LoginRoute: LoginRoute,
  OrgIndexRoute: OrgIndexRoute,
  AuthIndexRoute: AuthIndexRoute,
  OrgClassroomIndexRoute: OrgClassroomIndexRoute,
  OrgClassesIndexRoute: OrgClassesIndexRoute,
  OrgClassroomAssignmentsIndexRoute: OrgClassroomAssignmentsIndexRoute,
  OrgClassroomStudentsIndexRoute: OrgClassroomStudentsIndexRoute,
  OrgClassesNewIndexRoute: OrgClassesNewIndexRoute,
  OrgClassroomAssignmentsAssignmentIndexRoute:
    OrgClassroomAssignmentsAssignmentIndexRoute,
  OrgClassroomAssignmentsNewIndexRoute: OrgClassroomAssignmentsNewIndexRoute,
  OrgClassroomAssignmentsAssignmentAcceptIndexRoute:
    OrgClassroomAssignmentsAssignmentAcceptIndexRoute,
  OrgClassroomAssignmentsAssignmentSubmissionsIndexRoute:
    OrgClassroomAssignmentsAssignmentSubmissionsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
