/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ClassesRouteImport } from './routes/classes'
import { Route as AssignmentsRouteImport } from './routes/assignments'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrgClassroomStudentsIndexRouteImport } from './routes/$org/$classroom/students/index'
import { Route as OrgClassroomAssignmentsIndexRouteImport } from './routes/$org/$classroom/assignments/index'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassesRoute = ClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => rootRouteImport,
} as any)
const AssignmentsRoute = AssignmentsRouteImport.update({
  id: '/assignments',
  path: '/assignments',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgClassroomStudentsIndexRoute =
  OrgClassroomStudentsIndexRouteImport.update({
    id: '/$org/$classroom/students/',
    path: '/$org/$classroom/students/',
    getParentRoute: () => rootRouteImport,
  } as any)
const OrgClassroomAssignmentsIndexRoute =
  OrgClassroomAssignmentsIndexRouteImport.update({
    id: '/$org/$classroom/assignments/',
    path: '/$org/$classroom/assignments/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assignments': typeof AssignmentsRoute
  '/classes': typeof ClassesRoute
  '/login': typeof LoginRoute
  '/$org/$classroom/assignments/': typeof OrgClassroomAssignmentsIndexRoute
  '/$org/$classroom/students/': typeof OrgClassroomStudentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assignments': typeof AssignmentsRoute
  '/classes': typeof ClassesRoute
  '/login': typeof LoginRoute
  '/$org/$classroom/assignments': typeof OrgClassroomAssignmentsIndexRoute
  '/$org/$classroom/students': typeof OrgClassroomStudentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assignments': typeof AssignmentsRoute
  '/classes': typeof ClassesRoute
  '/login': typeof LoginRoute
  '/$org/$classroom/assignments/': typeof OrgClassroomAssignmentsIndexRoute
  '/$org/$classroom/students/': typeof OrgClassroomStudentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assignments'
    | '/classes'
    | '/login'
    | '/$org/$classroom/assignments/'
    | '/$org/$classroom/students/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assignments'
    | '/classes'
    | '/login'
    | '/$org/$classroom/assignments'
    | '/$org/$classroom/students'
  id:
    | '__root__'
    | '/'
    | '/assignments'
    | '/classes'
    | '/login'
    | '/$org/$classroom/assignments/'
    | '/$org/$classroom/students/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssignmentsRoute: typeof AssignmentsRoute
  ClassesRoute: typeof ClassesRoute
  LoginRoute: typeof LoginRoute
  OrgClassroomAssignmentsIndexRoute: typeof OrgClassroomAssignmentsIndexRoute
  OrgClassroomStudentsIndexRoute: typeof OrgClassroomStudentsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classes': {
      id: '/classes'
      path: '/classes'
      fullPath: '/classes'
      preLoaderRoute: typeof ClassesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assignments': {
      id: '/assignments'
      path: '/assignments'
      fullPath: '/assignments'
      preLoaderRoute: typeof AssignmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$org/$classroom/students/': {
      id: '/$org/$classroom/students/'
      path: '/$org/$classroom/students'
      fullPath: '/$org/$classroom/students/'
      preLoaderRoute: typeof OrgClassroomStudentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$org/$classroom/assignments/': {
      id: '/$org/$classroom/assignments/'
      path: '/$org/$classroom/assignments'
      fullPath: '/$org/$classroom/assignments/'
      preLoaderRoute: typeof OrgClassroomAssignmentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssignmentsRoute: AssignmentsRoute,
  ClassesRoute: ClassesRoute,
  LoginRoute: LoginRoute,
  OrgClassroomAssignmentsIndexRoute: OrgClassroomAssignmentsIndexRoute,
  OrgClassroomStudentsIndexRoute: OrgClassroomStudentsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
