/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ClassesRouteImport } from './routes/classes'
import { Route as AssignmentsRouteImport } from './routes/assignments'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as AuthedOrgIndexRouteImport } from './routes/_authed/$org/index'
import { Route as AuthedOrgSetupIndexRouteImport } from './routes/_authed/$org/setup/index'
import { Route as AuthedOrgSettingsIndexRouteImport } from './routes/_authed/$org/settings/index'
import { Route as AuthedOrgPublishedIndexRouteImport } from './routes/_authed/$org/published/index'
import { Route as AuthedOrgClassesIndexRouteImport } from './routes/_authed/$org/classes/index'
import { Route as AuthedOrgClassroomIndexRouteImport } from './routes/_authed/$org/$classroom/index'
import { Route as AuthedOrgClassesNewIndexRouteImport } from './routes/_authed/$org/classes/new/index'
import { Route as AuthedOrgClassroomStudentsIndexRouteImport } from './routes/_authed/$org/$classroom/students/index'
import { Route as AuthedOrgClassroomOnboardIndexRouteImport } from './routes/_authed/$org/$classroom/onboard/index'
import { Route as AuthedOrgClassroomEditIndexRouteImport } from './routes/_authed/$org/$classroom/edit/index'
import { Route as AuthedOrgClassroomAssignmentsIndexRouteImport } from './routes/_authed/$org/$classroom/assignments/index'
import { Route as AuthedOrgClassroomAssignmentsNewIndexRouteImport } from './routes/_authed/$org/$classroom/assignments/new/index'
import { Route as AuthedOrgClassroomAssignmentsAssignmentIndexRouteImport } from './routes/_authed/$org/$classroom/assignments/$assignment/index'
import { Route as AuthedOrgClassroomAssignmentsAssignmentSubmissionsIndexRouteImport } from './routes/_authed/$org/$classroom/assignments/$assignment/submissions/index'
import { Route as AuthedOrgClassroomAssignmentsAssignmentSubmissionIndexRouteImport } from './routes/_authed/$org/$classroom/assignments/$assignment/submission/index'
import { Route as AuthedOrgClassroomAssignmentsAssignmentEditIndexRouteImport } from './routes/_authed/$org/$classroom/assignments/$assignment/edit/index'
import { Route as AuthedOrgClassroomAssignmentsAssignmentAcceptIndexRouteImport } from './routes/_authed/$org/$classroom/assignments/$assignment/accept/index'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassesRoute = ClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => rootRouteImport,
} as any)
const AssignmentsRoute = AssignmentsRouteImport.update({
  id: '/assignments',
  path: '/assignments',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedOrgIndexRoute = AuthedOrgIndexRouteImport.update({
  id: '/$org/',
  path: '/$org/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedOrgSetupIndexRoute = AuthedOrgSetupIndexRouteImport.update({
  id: '/$org/setup/',
  path: '/$org/setup/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedOrgSettingsIndexRoute = AuthedOrgSettingsIndexRouteImport.update({
  id: '/$org/settings/',
  path: '/$org/settings/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedOrgPublishedIndexRoute = AuthedOrgPublishedIndexRouteImport.update({
  id: '/$org/published/',
  path: '/$org/published/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedOrgClassesIndexRoute = AuthedOrgClassesIndexRouteImport.update({
  id: '/$org/classes/',
  path: '/$org/classes/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedOrgClassroomIndexRoute = AuthedOrgClassroomIndexRouteImport.update({
  id: '/$org/$classroom/',
  path: '/$org/$classroom/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedOrgClassesNewIndexRoute =
  AuthedOrgClassesNewIndexRouteImport.update({
    id: '/$org/classes/new/',
    path: '/$org/classes/new/',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedOrgClassroomStudentsIndexRoute =
  AuthedOrgClassroomStudentsIndexRouteImport.update({
    id: '/$org/$classroom/students/',
    path: '/$org/$classroom/students/',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedOrgClassroomOnboardIndexRoute =
  AuthedOrgClassroomOnboardIndexRouteImport.update({
    id: '/$org/$classroom/onboard/',
    path: '/$org/$classroom/onboard/',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedOrgClassroomEditIndexRoute =
  AuthedOrgClassroomEditIndexRouteImport.update({
    id: '/$org/$classroom/edit/',
    path: '/$org/$classroom/edit/',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedOrgClassroomAssignmentsIndexRoute =
  AuthedOrgClassroomAssignmentsIndexRouteImport.update({
    id: '/$org/$classroom/assignments/',
    path: '/$org/$classroom/assignments/',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedOrgClassroomAssignmentsNewIndexRoute =
  AuthedOrgClassroomAssignmentsNewIndexRouteImport.update({
    id: '/$org/$classroom/assignments/new/',
    path: '/$org/$classroom/assignments/new/',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedOrgClassroomAssignmentsAssignmentIndexRoute =
  AuthedOrgClassroomAssignmentsAssignmentIndexRouteImport.update({
    id: '/$org/$classroom/assignments/$assignment/',
    path: '/$org/$classroom/assignments/$assignment/',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedOrgClassroomAssignmentsAssignmentSubmissionsIndexRoute =
  AuthedOrgClassroomAssignmentsAssignmentSubmissionsIndexRouteImport.update({
    id: '/$org/$classroom/assignments/$assignment/submissions/',
    path: '/$org/$classroom/assignments/$assignment/submissions/',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedOrgClassroomAssignmentsAssignmentSubmissionIndexRoute =
  AuthedOrgClassroomAssignmentsAssignmentSubmissionIndexRouteImport.update({
    id: '/$org/$classroom/assignments/$assignment/submission/',
    path: '/$org/$classroom/assignments/$assignment/submission/',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedOrgClassroomAssignmentsAssignmentEditIndexRoute =
  AuthedOrgClassroomAssignmentsAssignmentEditIndexRouteImport.update({
    id: '/$org/$classroom/assignments/$assignment/edit/',
    path: '/$org/$classroom/assignments/$assignment/edit/',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedOrgClassroomAssignmentsAssignmentAcceptIndexRoute =
  AuthedOrgClassroomAssignmentsAssignmentAcceptIndexRouteImport.update({
    id: '/$org/$classroom/assignments/$assignment/accept/',
    path: '/$org/$classroom/assignments/$assignment/accept/',
    getParentRoute: () => AuthedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/assignments': typeof AssignmentsRoute
  '/classes': typeof ClassesRoute
  '/login': typeof LoginRoute
  '/auth/': typeof AuthIndexRoute
  '/$org/': typeof AuthedOrgIndexRoute
  '/$org/$classroom/': typeof AuthedOrgClassroomIndexRoute
  '/$org/classes/': typeof AuthedOrgClassesIndexRoute
  '/$org/published/': typeof AuthedOrgPublishedIndexRoute
  '/$org/settings/': typeof AuthedOrgSettingsIndexRoute
  '/$org/setup/': typeof AuthedOrgSetupIndexRoute
  '/$org/$classroom/assignments/': typeof AuthedOrgClassroomAssignmentsIndexRoute
  '/$org/$classroom/edit/': typeof AuthedOrgClassroomEditIndexRoute
  '/$org/$classroom/onboard/': typeof AuthedOrgClassroomOnboardIndexRoute
  '/$org/$classroom/students/': typeof AuthedOrgClassroomStudentsIndexRoute
  '/$org/classes/new/': typeof AuthedOrgClassesNewIndexRoute
  '/$org/$classroom/assignments/$assignment/': typeof AuthedOrgClassroomAssignmentsAssignmentIndexRoute
  '/$org/$classroom/assignments/new/': typeof AuthedOrgClassroomAssignmentsNewIndexRoute
  '/$org/$classroom/assignments/$assignment/accept/': typeof AuthedOrgClassroomAssignmentsAssignmentAcceptIndexRoute
  '/$org/$classroom/assignments/$assignment/edit/': typeof AuthedOrgClassroomAssignmentsAssignmentEditIndexRoute
  '/$org/$classroom/assignments/$assignment/submission/': typeof AuthedOrgClassroomAssignmentsAssignmentSubmissionIndexRoute
  '/$org/$classroom/assignments/$assignment/submissions/': typeof AuthedOrgClassroomAssignmentsAssignmentSubmissionsIndexRoute
}
export interface FileRoutesByTo {
  '/assignments': typeof AssignmentsRoute
  '/classes': typeof ClassesRoute
  '/login': typeof LoginRoute
  '/': typeof AuthedIndexRoute
  '/auth': typeof AuthIndexRoute
  '/$org': typeof AuthedOrgIndexRoute
  '/$org/$classroom': typeof AuthedOrgClassroomIndexRoute
  '/$org/classes': typeof AuthedOrgClassesIndexRoute
  '/$org/published': typeof AuthedOrgPublishedIndexRoute
  '/$org/settings': typeof AuthedOrgSettingsIndexRoute
  '/$org/setup': typeof AuthedOrgSetupIndexRoute
  '/$org/$classroom/assignments': typeof AuthedOrgClassroomAssignmentsIndexRoute
  '/$org/$classroom/edit': typeof AuthedOrgClassroomEditIndexRoute
  '/$org/$classroom/onboard': typeof AuthedOrgClassroomOnboardIndexRoute
  '/$org/$classroom/students': typeof AuthedOrgClassroomStudentsIndexRoute
  '/$org/classes/new': typeof AuthedOrgClassesNewIndexRoute
  '/$org/$classroom/assignments/$assignment': typeof AuthedOrgClassroomAssignmentsAssignmentIndexRoute
  '/$org/$classroom/assignments/new': typeof AuthedOrgClassroomAssignmentsNewIndexRoute
  '/$org/$classroom/assignments/$assignment/accept': typeof AuthedOrgClassroomAssignmentsAssignmentAcceptIndexRoute
  '/$org/$classroom/assignments/$assignment/edit': typeof AuthedOrgClassroomAssignmentsAssignmentEditIndexRoute
  '/$org/$classroom/assignments/$assignment/submission': typeof AuthedOrgClassroomAssignmentsAssignmentSubmissionIndexRoute
  '/$org/$classroom/assignments/$assignment/submissions': typeof AuthedOrgClassroomAssignmentsAssignmentSubmissionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/assignments': typeof AssignmentsRoute
  '/classes': typeof ClassesRoute
  '/login': typeof LoginRoute
  '/_authed/': typeof AuthedIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/_authed/$org/': typeof AuthedOrgIndexRoute
  '/_authed/$org/$classroom/': typeof AuthedOrgClassroomIndexRoute
  '/_authed/$org/classes/': typeof AuthedOrgClassesIndexRoute
  '/_authed/$org/published/': typeof AuthedOrgPublishedIndexRoute
  '/_authed/$org/settings/': typeof AuthedOrgSettingsIndexRoute
  '/_authed/$org/setup/': typeof AuthedOrgSetupIndexRoute
  '/_authed/$org/$classroom/assignments/': typeof AuthedOrgClassroomAssignmentsIndexRoute
  '/_authed/$org/$classroom/edit/': typeof AuthedOrgClassroomEditIndexRoute
  '/_authed/$org/$classroom/onboard/': typeof AuthedOrgClassroomOnboardIndexRoute
  '/_authed/$org/$classroom/students/': typeof AuthedOrgClassroomStudentsIndexRoute
  '/_authed/$org/classes/new/': typeof AuthedOrgClassesNewIndexRoute
  '/_authed/$org/$classroom/assignments/$assignment/': typeof AuthedOrgClassroomAssignmentsAssignmentIndexRoute
  '/_authed/$org/$classroom/assignments/new/': typeof AuthedOrgClassroomAssignmentsNewIndexRoute
  '/_authed/$org/$classroom/assignments/$assignment/accept/': typeof AuthedOrgClassroomAssignmentsAssignmentAcceptIndexRoute
  '/_authed/$org/$classroom/assignments/$assignment/edit/': typeof AuthedOrgClassroomAssignmentsAssignmentEditIndexRoute
  '/_authed/$org/$classroom/assignments/$assignment/submission/': typeof AuthedOrgClassroomAssignmentsAssignmentSubmissionIndexRoute
  '/_authed/$org/$classroom/assignments/$assignment/submissions/': typeof AuthedOrgClassroomAssignmentsAssignmentSubmissionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assignments'
    | '/classes'
    | '/login'
    | '/auth/'
    | '/$org/'
    | '/$org/$classroom/'
    | '/$org/classes/'
    | '/$org/published/'
    | '/$org/settings/'
    | '/$org/setup/'
    | '/$org/$classroom/assignments/'
    | '/$org/$classroom/edit/'
    | '/$org/$classroom/onboard/'
    | '/$org/$classroom/students/'
    | '/$org/classes/new/'
    | '/$org/$classroom/assignments/$assignment/'
    | '/$org/$classroom/assignments/new/'
    | '/$org/$classroom/assignments/$assignment/accept/'
    | '/$org/$classroom/assignments/$assignment/edit/'
    | '/$org/$classroom/assignments/$assignment/submission/'
    | '/$org/$classroom/assignments/$assignment/submissions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/assignments'
    | '/classes'
    | '/login'
    | '/'
    | '/auth'
    | '/$org'
    | '/$org/$classroom'
    | '/$org/classes'
    | '/$org/published'
    | '/$org/settings'
    | '/$org/setup'
    | '/$org/$classroom/assignments'
    | '/$org/$classroom/edit'
    | '/$org/$classroom/onboard'
    | '/$org/$classroom/students'
    | '/$org/classes/new'
    | '/$org/$classroom/assignments/$assignment'
    | '/$org/$classroom/assignments/new'
    | '/$org/$classroom/assignments/$assignment/accept'
    | '/$org/$classroom/assignments/$assignment/edit'
    | '/$org/$classroom/assignments/$assignment/submission'
    | '/$org/$classroom/assignments/$assignment/submissions'
  id:
    | '__root__'
    | '/_authed'
    | '/assignments'
    | '/classes'
    | '/login'
    | '/_authed/'
    | '/auth/'
    | '/_authed/$org/'
    | '/_authed/$org/$classroom/'
    | '/_authed/$org/classes/'
    | '/_authed/$org/published/'
    | '/_authed/$org/settings/'
    | '/_authed/$org/setup/'
    | '/_authed/$org/$classroom/assignments/'
    | '/_authed/$org/$classroom/edit/'
    | '/_authed/$org/$classroom/onboard/'
    | '/_authed/$org/$classroom/students/'
    | '/_authed/$org/classes/new/'
    | '/_authed/$org/$classroom/assignments/$assignment/'
    | '/_authed/$org/$classroom/assignments/new/'
    | '/_authed/$org/$classroom/assignments/$assignment/accept/'
    | '/_authed/$org/$classroom/assignments/$assignment/edit/'
    | '/_authed/$org/$classroom/assignments/$assignment/submission/'
    | '/_authed/$org/$classroom/assignments/$assignment/submissions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  AssignmentsRoute: typeof AssignmentsRoute
  ClassesRoute: typeof ClassesRoute
  LoginRoute: typeof LoginRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classes': {
      id: '/classes'
      path: '/classes'
      fullPath: '/classes'
      preLoaderRoute: typeof ClassesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assignments': {
      id: '/assignments'
      path: '/assignments'
      fullPath: '/assignments'
      preLoaderRoute: typeof AssignmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/auth'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/$org/': {
      id: '/_authed/$org/'
      path: '/$org'
      fullPath: '/$org/'
      preLoaderRoute: typeof AuthedOrgIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/$org/setup/': {
      id: '/_authed/$org/setup/'
      path: '/$org/setup'
      fullPath: '/$org/setup/'
      preLoaderRoute: typeof AuthedOrgSetupIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/$org/settings/': {
      id: '/_authed/$org/settings/'
      path: '/$org/settings'
      fullPath: '/$org/settings/'
      preLoaderRoute: typeof AuthedOrgSettingsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/$org/published/': {
      id: '/_authed/$org/published/'
      path: '/$org/published'
      fullPath: '/$org/published/'
      preLoaderRoute: typeof AuthedOrgPublishedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/$org/classes/': {
      id: '/_authed/$org/classes/'
      path: '/$org/classes'
      fullPath: '/$org/classes/'
      preLoaderRoute: typeof AuthedOrgClassesIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/$org/$classroom/': {
      id: '/_authed/$org/$classroom/'
      path: '/$org/$classroom'
      fullPath: '/$org/$classroom/'
      preLoaderRoute: typeof AuthedOrgClassroomIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/$org/classes/new/': {
      id: '/_authed/$org/classes/new/'
      path: '/$org/classes/new'
      fullPath: '/$org/classes/new/'
      preLoaderRoute: typeof AuthedOrgClassesNewIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/$org/$classroom/students/': {
      id: '/_authed/$org/$classroom/students/'
      path: '/$org/$classroom/students'
      fullPath: '/$org/$classroom/students/'
      preLoaderRoute: typeof AuthedOrgClassroomStudentsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/$org/$classroom/onboard/': {
      id: '/_authed/$org/$classroom/onboard/'
      path: '/$org/$classroom/onboard'
      fullPath: '/$org/$classroom/onboard/'
      preLoaderRoute: typeof AuthedOrgClassroomOnboardIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/$org/$classroom/edit/': {
      id: '/_authed/$org/$classroom/edit/'
      path: '/$org/$classroom/edit'
      fullPath: '/$org/$classroom/edit/'
      preLoaderRoute: typeof AuthedOrgClassroomEditIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/$org/$classroom/assignments/': {
      id: '/_authed/$org/$classroom/assignments/'
      path: '/$org/$classroom/assignments'
      fullPath: '/$org/$classroom/assignments/'
      preLoaderRoute: typeof AuthedOrgClassroomAssignmentsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/$org/$classroom/assignments/new/': {
      id: '/_authed/$org/$classroom/assignments/new/'
      path: '/$org/$classroom/assignments/new'
      fullPath: '/$org/$classroom/assignments/new/'
      preLoaderRoute: typeof AuthedOrgClassroomAssignmentsNewIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/$org/$classroom/assignments/$assignment/': {
      id: '/_authed/$org/$classroom/assignments/$assignment/'
      path: '/$org/$classroom/assignments/$assignment'
      fullPath: '/$org/$classroom/assignments/$assignment/'
      preLoaderRoute: typeof AuthedOrgClassroomAssignmentsAssignmentIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/$org/$classroom/assignments/$assignment/submissions/': {
      id: '/_authed/$org/$classroom/assignments/$assignment/submissions/'
      path: '/$org/$classroom/assignments/$assignment/submissions'
      fullPath: '/$org/$classroom/assignments/$assignment/submissions/'
      preLoaderRoute: typeof AuthedOrgClassroomAssignmentsAssignmentSubmissionsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/$org/$classroom/assignments/$assignment/submission/': {
      id: '/_authed/$org/$classroom/assignments/$assignment/submission/'
      path: '/$org/$classroom/assignments/$assignment/submission'
      fullPath: '/$org/$classroom/assignments/$assignment/submission/'
      preLoaderRoute: typeof AuthedOrgClassroomAssignmentsAssignmentSubmissionIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/$org/$classroom/assignments/$assignment/edit/': {
      id: '/_authed/$org/$classroom/assignments/$assignment/edit/'
      path: '/$org/$classroom/assignments/$assignment/edit'
      fullPath: '/$org/$classroom/assignments/$assignment/edit/'
      preLoaderRoute: typeof AuthedOrgClassroomAssignmentsAssignmentEditIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/$org/$classroom/assignments/$assignment/accept/': {
      id: '/_authed/$org/$classroom/assignments/$assignment/accept/'
      path: '/$org/$classroom/assignments/$assignment/accept'
      fullPath: '/$org/$classroom/assignments/$assignment/accept/'
      preLoaderRoute: typeof AuthedOrgClassroomAssignmentsAssignmentAcceptIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedIndexRoute: typeof AuthedIndexRoute
  AuthedOrgIndexRoute: typeof AuthedOrgIndexRoute
  AuthedOrgClassroomIndexRoute: typeof AuthedOrgClassroomIndexRoute
  AuthedOrgClassesIndexRoute: typeof AuthedOrgClassesIndexRoute
  AuthedOrgPublishedIndexRoute: typeof AuthedOrgPublishedIndexRoute
  AuthedOrgSettingsIndexRoute: typeof AuthedOrgSettingsIndexRoute
  AuthedOrgSetupIndexRoute: typeof AuthedOrgSetupIndexRoute
  AuthedOrgClassroomAssignmentsIndexRoute: typeof AuthedOrgClassroomAssignmentsIndexRoute
  AuthedOrgClassroomEditIndexRoute: typeof AuthedOrgClassroomEditIndexRoute
  AuthedOrgClassroomOnboardIndexRoute: typeof AuthedOrgClassroomOnboardIndexRoute
  AuthedOrgClassroomStudentsIndexRoute: typeof AuthedOrgClassroomStudentsIndexRoute
  AuthedOrgClassesNewIndexRoute: typeof AuthedOrgClassesNewIndexRoute
  AuthedOrgClassroomAssignmentsAssignmentIndexRoute: typeof AuthedOrgClassroomAssignmentsAssignmentIndexRoute
  AuthedOrgClassroomAssignmentsNewIndexRoute: typeof AuthedOrgClassroomAssignmentsNewIndexRoute
  AuthedOrgClassroomAssignmentsAssignmentAcceptIndexRoute: typeof AuthedOrgClassroomAssignmentsAssignmentAcceptIndexRoute
  AuthedOrgClassroomAssignmentsAssignmentEditIndexRoute: typeof AuthedOrgClassroomAssignmentsAssignmentEditIndexRoute
  AuthedOrgClassroomAssignmentsAssignmentSubmissionIndexRoute: typeof AuthedOrgClassroomAssignmentsAssignmentSubmissionIndexRoute
  AuthedOrgClassroomAssignmentsAssignmentSubmissionsIndexRoute: typeof AuthedOrgClassroomAssignmentsAssignmentSubmissionsIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedIndexRoute: AuthedIndexRoute,
  AuthedOrgIndexRoute: AuthedOrgIndexRoute,
  AuthedOrgClassroomIndexRoute: AuthedOrgClassroomIndexRoute,
  AuthedOrgClassesIndexRoute: AuthedOrgClassesIndexRoute,
  AuthedOrgPublishedIndexRoute: AuthedOrgPublishedIndexRoute,
  AuthedOrgSettingsIndexRoute: AuthedOrgSettingsIndexRoute,
  AuthedOrgSetupIndexRoute: AuthedOrgSetupIndexRoute,
  AuthedOrgClassroomAssignmentsIndexRoute:
    AuthedOrgClassroomAssignmentsIndexRoute,
  AuthedOrgClassroomEditIndexRoute: AuthedOrgClassroomEditIndexRoute,
  AuthedOrgClassroomOnboardIndexRoute: AuthedOrgClassroomOnboardIndexRoute,
  AuthedOrgClassroomStudentsIndexRoute: AuthedOrgClassroomStudentsIndexRoute,
  AuthedOrgClassesNewIndexRoute: AuthedOrgClassesNewIndexRoute,
  AuthedOrgClassroomAssignmentsAssignmentIndexRoute:
    AuthedOrgClassroomAssignmentsAssignmentIndexRoute,
  AuthedOrgClassroomAssignmentsNewIndexRoute:
    AuthedOrgClassroomAssignmentsNewIndexRoute,
  AuthedOrgClassroomAssignmentsAssignmentAcceptIndexRoute:
    AuthedOrgClassroomAssignmentsAssignmentAcceptIndexRoute,
  AuthedOrgClassroomAssignmentsAssignmentEditIndexRoute:
    AuthedOrgClassroomAssignmentsAssignmentEditIndexRoute,
  AuthedOrgClassroomAssignmentsAssignmentSubmissionIndexRoute:
    AuthedOrgClassroomAssignmentsAssignmentSubmissionIndexRoute,
  AuthedOrgClassroomAssignmentsAssignmentSubmissionsIndexRoute:
    AuthedOrgClassroomAssignmentsAssignmentSubmissionsIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  AssignmentsRoute: AssignmentsRoute,
  ClassesRoute: ClassesRoute,
  LoginRoute: LoginRoute,
  AuthIndexRoute: AuthIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
